### PR TITLE
Fix InScatter Jacobian term for Serpent cross sections

### LINKED ISSUE #160: Fix InScatter kernel OffDiagJacobian formulation for simulations using Serpent 2 group data
The current formulation for the OffDiagJacobian term in the `InScatter` kernel is wrong for users who use group constant data.

The `InScatter` kernel uses an `sss2_input` flag to determine whether the group constant data provided by the user is from SCALE or Serpent 2. This is especially important for the in-scattering term of the neutron diffusion equations because the indexing of the in-scattering cross section values are different between SCALE and Serpent 2.

The formulation for the Residual term correctly uses the `sss2_input` flag:
```
Real
InScatter::computeQpResidual()
{
  Real r = 0;
  for (unsigned int i = 0; i < _num_groups; ++i)
  {
    if (i == _group)
      continue;
    if (_sss2_input)
      r += -_test[_i][_qp] * _gtransfxs[_qp][i * _num_groups + _group] *
           computeConcentration((*_group_fluxes[i]), _qp);
    else
      r += -_test[_i][_qp] * _gtransfxs[_qp][i + _group * _num_groups] *
           computeConcentration((*_group_fluxes[i]), _qp);
  }

  return r;
}
```

The section containing the erroneous formulation for the OffDiagJacobian term is:
```
  if (jvar == _temp_id)
  {
    for (unsigned int i = 0; i < _num_groups; ++i)
    {
      if (i == _group)
        continue;
      jac += -_test[_i][_qp] * _d_gtransfxs_d_temp[_qp][i + _group * _num_groups] * _phi[_j][_qp] *
             computeConcentration((*_group_fluxes[i]), _qp);
    }
  }
```

Instead, it should be:
```
  if (jvar == _temp_id)
  {
    for (unsigned int i = 0; i < _num_groups; ++i)
    {
      if (i == _group)
        continue;
      if (_sss2_input)
        jac += -_test[_i][_qp] * _d_gtransfxs_d_temp[_qp][i * _num_groups + _group] * _phi[_j][_qp] *
               computeConcentration((*_group_fluxes[i]), _qp);
      else
        jac += -_test[_i][_qp] * _d_gtransfxs_d_temp[_qp][i + _group * _num_groups] * _phi[_j][_qp] *
               computeConcentration((*_group_fluxes[i]), _qp);
    }
  }
```

### PR DESCRIPTION
**Pull request by smpark7**
Closes #160 

This PR fixes the `OffDiagJacobian` formulation for the `InScatter` kernel. In particular, the `OffDiagJacobian` formulation for the derivative of the group flux scattering term with respect to temperature is wrong when running a simulation with Serpent cross sections. This is because the scattering matrix from Serpent is the transpose of the matrix from SCALE. The `Residual` formulation in `InScatter` reflects the correct indexing in the `if` loops.

For the new test concerning Serpent cross sections, I replicated the coupled neutronics/temperature test from `twod_axi_coupled/auto_diff_rho.i`. I copied the `newt_msre_fuel_*` and `newt_msre_mod_*` SCALE cross section txt files in `property_file_dir` and converted them to mimic cross section files from Serpent by:
1. Renaming the postfixes of the filenames based on Serpent's naming convention, i.e. `FISSE`->`KAPPA`, `FISSXS`->`FISS`, `RECIPVEL`->`INVV`, `DECAY_CONSTANT`->`LAMBDA`, `GTRANSFX`->`SP0`.
2. Transposing the scattering cross section matrix in `SP0`.

I created a new test input file `auto_diff_rho_serpent.i` from `auto_diff_rho.i` by changing the provided cross section file paths to the converted cross section files I placed in `$MOLTRES/property_file_dir/newt_msre_converted_to_serpent`.

`auto_diff_rho.i` is a transient simulation of a 2D MSRE-based geometry towards steady state with adaptive time-stepping. In the old `auto_diff_rho.i`, the simulation stops when it reaches an `end_time` of 10000s, long after steady state is reached at t\~1000s. However, the convergence criteria in the `Executioner` settings are too lenient to catch minor errors in Jacobian formulations. For example, the present error in the `InScatter` Jacobian formulation allows the simulation to trudge along with smaller timesteps (dt\~0.1s) towards t=10000s. Therefore, I changed the stop criteria by setting a maximum 80 timesteps allowed, reducing the optimal iterations to 5, and turned on automatic steady state detection. The new setup typically reaches steady state by the 67th timestep at t=1009.51s. Without the fix to `InScatter`, `auto_diff_rho_serpent.i` terminates after 80 timesteps at t\~7.96249s without reaching steady state.

### CODE REVIEW

File: src/kernels/InScatter.C [hunk 1]
```diff
@@ -91,8 +91,12 @@ InScatter::computeQpOffDiagJacobian(unsigned int jvar)
     {
       if (i == _group)
         continue;
-      jac += -_test[_i][_qp] * _d_gtransfxs_d_temp[_qp][i + _group * _num_groups] * _phi[_j][_qp] *
-             computeConcentration((*_group_fluxes[i]), _qp);
+      if (_sss2_input)
```
Comment (gwenchee) [inline src/kernels/InScatter.C:94]: I'm planning to add the option to use OpenMC group constants. Will I need to touch this part? Depending on if openmc returns the scattering matrix as a transpose or not?

**Review by gwenchee — APPROVED** [review]
LGTM!

File: src/kernels/InScatter.C (hunk 1 above)
Comment (smpark7) [reply src/kernels/InScatter.C:94]: Yes, moving forward, we'll have to decide whether to standardize the cross section format or to handle each case differently like the current approach
